USE QLDUAN
GO
----1.Viết stored procedure tạo mã khách hàng
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME  = 'pr_TAOMAKH')
	DROP PROCEDURE pr_TAOMAKH
GO
CREATE PROCEDURE pr_TAOMAKH
AS
BEGIN
	------------------1.Chưa có khách hàng
	IF NOT EXISTS(SELECT * FROM KHACHHANG)
		SELECT 'KH' +  CAST(YEAR(GETDATE()) AS VARCHAR) + 
				   CAST(MONTH(GETDATE()) AS VARCHAR) + 
					   CAST(DAY(GETDATE()) AS VARCHAR) + '001'
	ELSE ------------------2.Đã có khách hàng
	BEGIN
		DECLARE	@KH1	VARCHAR(15),
				@KH2	VARCHAR(15)
		SELECT @KH1 = MAX(MSKH) FROM KHACHHANG
		---SELECT  MAX(MSKH) FROM KHACHHANG
		SET @KH2 = RIGHT(RTRIM(@KH1), 3) + 1
		IF LEN(@KH2)=1
			SELECT	'KH' +CAST(YEAR(GETDATE()) AS VARCHAR) + 
					      CAST(MONTH(GETDATE()) AS VARCHAR) + 
				     	  CAST(DAY(GETDATE()) AS VARCHAR) + '00' + @KH2
		ELSE
			IF LEN(@KH2)=2
				SELECT	'KH' + CAST(YEAR(GETDATE()) AS VARCHAR) + 
						CAST(MONTH(GETDATE()) AS VARCHAR) + 
						CAST(DAY(GETDATE()) AS VARCHAR) + '0' + @KH2
			ELSE
				IF LEN(@KH2)=3
					SELECT	'KH' + CAST(YEAR(GETDATE()) AS VARCHAR) + 
							CAST(MONTH(GETDATE()) AS VARCHAR) + 
							CAST(DAY(GETDATE()) AS VARCHAR) + @KH2
	END
END
GO
/*
	EXEC pr_TAOMAKH
*/
----1.Viết stored procedure tạo mã khách hàng
GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME = 'pr_THEMKH')
	DROP PROCEDURE pr_THEMKH
GO
CREATE PROCEDURE pr_THEMKH
(
	@MsKH			CHAR(15), 
	@TENKH			NVARCHAR(50), 
	@PHAI			NCHAR(5), 
	@DIACHI			NVARCHAR(100), 
	@DIENTHOAI		VARCHAR(10)
)
AS
BEGIN
	IF EXISTS(SELECT * FROM KHACHHANG WHERE MsKH = @MsKH)
		RAISERROR(N'Mã số khách hàng này đã tồn tại', 16, 1)
	ELSE
	BEGIN
		INSERT INTO KHACHHANG(MsKH, TENKH, PHAI, DIACHI, DIENTHOAI)
			VALUES(@MsKH, @TENKH, @PHAI, @DIACHI, @DIENTHOAI)
		RAISERROR(N'Thêm khách hàng [%s] thành công!', 16, 1, @TENKH)
	END
END
GO
/*
	EXEC pr_THEMKH	@MsKH = 'KH20211127007', @TENKH = N'Nguyễn Anh Bình', 
					@PHAI = 'Nam', @DIACHI = '12 - An Phú Đông - Q.12 - HCM', @DIENTHOAI = '0903987645'
*/
GO
SELECT * FROM KHACHHANG
SELECT * FROM HOADON
SELECT GETDATE()
SELECT 006 + 1